### ISSUE TITLE
Publish visualize and manage playlist 

### ISSUE THREAD

**Issue by SquadTuring1** [SquadTuring1/final-project-front#25]
- [ ] list of user playlist 
- [ ] manual ordering the list of playlists 
- [ ] create playlist 
- [ ] edit playlist 
- [ ] playlist view 
- [ ] delete playlist 
- [ ] follow playlist 
- [ ] add song to playlist from playlist 
- [ ] option menu inside playlist 
- [ ] add to playlist form the song view
- [ ] Delete song from inside a playlist
