### ISSUE TITLE
Account management

### ISSUE THREAD

**Issue by SquadTuring1** [SquadTuring1/final-project-front#7]
- [ ] visualize user information
- [ ] edit user information 
- [ ] change user password
